### PR TITLE
Added images to suppliers under the map

### PR DESCRIPTION
**Pull request by puranik9**
# Issue NUMBER(ON WAFFLE)
Closes #ISSUENUMBER

#Changes in this pull request

#Screenshot or Gif of the FEATURE/THEME CHANGE/ OR VISUAL CHANGE
screen shot 2018-03-28 at 10 19 43 pm

### CODE REVIEW

**Review by luantran — COMMENTED** [review]
please add the images to products as well

**Review by luantran — CHANGES_REQUESTED** [review]
Please add images to info windows

**Comment by puranik9** [comment]
Working on it

**Comment by puranik9** [comment]
Images can be seen in the Supplier info window as well (i.e. hovering over the map markers)

screen shot 2018-03-28 at 11 41 19 pm
screen shot 2018-03-28 at 11 41 28 pm

**Review by luantran — DISMISSED** [review]
Looks good

**Review by luantran — APPROVED** [review]
Looks good

**Pull request merged**
